export const GET_CHARACTER_SUCCESS = 'GET_CHARACTER_SUCCESS';
export const GET_CHARACTER_ERROR = 'GET_CHARACTER_ERROR';

export const GET_PLANET_SUCCESS = 'GET_PLANET_SUCCESS';
export const GET_PLANET_ERROR = 'GET_PLANET_ERROR';

export const GET_STARSHIP_SUCCESS = 'GET_STARSHIP_SUCCESS';
export const GET_STARSHIP_ERROR = 'GET_STARSHIP_ERROR';

export const GET_SEARCH_QUERIES_SUCCESS = 'GET_SEARCH_QUERIES_SUCCESS';
export const GET_SEARCH_QUERIES_ERROR = 'GET_SEARCH_QUERIES_ERROR';
